theme: jekyll-theme-minimal
title: [SplitRatioEstimator]
description: [Android app for a measurement study designed to collect data on network stationarity in cell phones.]
logo: /assets/images/logo.png
show_downloads: ["true"]
apk_url: https://drive.google.com/file/d/1M5ID_rp7i7d1kFPOy1y8tpdFBzTIRBWe/view?usp=sharing
