theme: jekyll-theme-minimal
title: [SplitRatioEstimator]
description: [This website is for a measurement study designed to collect data on network stationarity in cell phones.]
logo: /assets/images/logo.png
show_downloads: ["true"]

