theme: jekyll-theme-minimal
title: [SplitRatioEstimator]
description: [Android app for a measurement study designed to collect data on network stationarity in cell phones.]
logo: /assets/images/logo.png
show_downloads: ["true"]
apk_url: https://drive.google.com/file/d/19gpRoRwuG6vc7obyPArg7-D80YPh3Z65/view?usp=sharing
